export const CURTA_ABI = [
  {
    inputs: [
      { internalType: 'contract AuthorshipToken', name: '_authorshipToken', type: 'address' },
      { internalType: 'contract FlagRenderer', name: '_flagRenderer', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenId', type: 'uint256' }],
    name: 'AuthorshipTokenAlreadyUsed',
    type: 'error',
  },
  { inputs: [], name: 'IncorrectSolution', type: 'error' },
  { inputs: [], name: 'InsufficientFunds', type: 'error' },
  {
    inputs: [{ internalType: 'uint32', name: '_puzzleId', type: 'uint32' }],
    name: 'PuzzleAlreadyFermat',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_puzzleId', type: 'uint32' }],
    name: 'PuzzleAlreadySolved',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_puzzleId', type: 'uint32' }],
    name: 'PuzzleDoesNotExist',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_puzzleId', type: 'uint32' }],
    name: 'PuzzleNotFermat',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_puzzleId', type: 'uint32' }],
    name: 'PuzzleNotSolved',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_puzzleId', type: 'uint32' }],
    name: 'SubmissionClosed',
    type: 'error',
  },
  { inputs: [], name: 'Unauthorized', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint32', name: 'id', type: 'uint32' },
      { indexed: true, internalType: 'address', name: 'author', type: 'address' },
      { indexed: false, internalType: 'contract IPuzzle', name: 'puzzle', type: 'address' },
    ],
    name: 'AddPuzzle',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'spender', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'operator', type: 'address' },
      { indexed: false, internalType: 'bool', name: 'approved', type: 'bool' },
    ],
    name: 'ApprovalForAll',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint32', name: 'id', type: 'uint32' },
      { indexed: true, internalType: 'address', name: 'solver', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'solution', type: 'uint256' },
      { indexed: false, internalType: 'uint8', name: 'phase', type: 'uint8' },
    ],
    name: 'SolvePuzzle',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      { indexed: true, internalType: 'address', name: 'to', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    name: 'Transfer',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint32', name: 'id', type: 'uint32' },
      { indexed: false, internalType: 'uint256', name: 'colors', type: 'uint256' },
    ],
    name: 'UpdatePuzzleColors',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'contract IPuzzle', name: '_puzzle', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
    ],
    name: 'addPuzzle',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_spender', type: 'address' },
      { internalType: 'uint256', name: '_id', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'authorshipToken',
    outputs: [{ internalType: 'contract AuthorshipToken', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'fermat',
    outputs: [
      { internalType: 'uint32', name: 'puzzleId', type: 'uint32' },
      { internalType: 'uint40', name: 'timeTaken', type: 'uint40' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'flagRenderer',
    outputs: [{ internalType: 'contract FlagRenderer', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'getApproved',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    name: 'getPuzzle',
    outputs: [
      { internalType: 'contract IPuzzle', name: 'puzzle', type: 'address' },
      { internalType: 'uint40', name: 'addedTimestamp', type: 'uint40' },
      { internalType: 'uint40', name: 'firstSolveTimestamp', type: 'uint40' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    name: 'getPuzzleAuthor',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    name: 'getPuzzleColorsAndSolves',
    outputs: [
      { internalType: 'uint120', name: 'colors', type: 'uint120' },
      { internalType: 'uint32', name: 'phase0Solves', type: 'uint32' },
      { internalType: 'uint32', name: 'phase1Solves', type: 'uint32' },
      { internalType: 'uint32', name: 'phase2Solves', type: 'uint32' },
      { internalType: 'uint32', name: 'solves', type: 'uint32' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'getTokenData',
    outputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'uint40', name: 'solveTimestamp', type: 'uint40' },
      { internalType: 'uint56', name: 'solveMetadata', type: 'uint56' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'getUserBalances',
    outputs: [
      { internalType: 'uint32', name: 'phase0Solves', type: 'uint32' },
      { internalType: 'uint32', name: 'phase1Solves', type: 'uint32' },
      { internalType: 'uint32', name: 'phase2Solves', type: 'uint32' },
      { internalType: 'uint32', name: 'solves', type: 'uint32' },
      { internalType: 'uint32', name: 'balance', type: 'uint32' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint32', name: '', type: 'uint32' },
    ],
    name: 'hasSolvedPuzzle',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'hasUsedAuthorshipToken',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: '', type: 'address' },
    ],
    name: 'isApprovedForAll',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'name',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'puzzleId',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_from', type: 'address' },
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint256', name: '_id', type: 'uint256' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_from', type: 'address' },
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint256', name: '_id', type: 'uint256' },
      { internalType: 'bytes', name: '_data', type: 'bytes' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_operator', type: 'address' },
      { internalType: 'bool', name: '_approved', type: 'bool' },
    ],
    name: 'setApprovalForAll',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_puzzleId', type: 'uint32' }],
    name: 'setFermat',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint32', name: '_puzzleId', type: 'uint32' },
      { internalType: 'uint120', name: '_colors', type: 'uint120' },
    ],
    name: 'setPuzzleColors',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint32', name: '_puzzleId', type: 'uint32' },
      { internalType: 'uint256', name: '_solution', type: 'uint256' },
    ],
    name: 'solve',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: '_interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenId', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_from', type: 'address' },
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint256', name: '_id', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
