export const OPCODES_SHANGHAI: { [key: number]: { category: string; name: string } } = {
  // Stop
  0x00: { category: 'Stop', name: 'STOP' },
  // Arithmetic
  0x01: { category: 'Arithmethic', name: 'ADD' },
  0x02: { category: 'Arithmethic', name: 'MUL' },
  0x03: { category: 'Arithmethic', name: 'SUB' },
  0x04: { category: 'Arithmethic', name: 'DIV' },
  0x05: { category: 'Arithmethic', name: 'SDIV' },
  0x06: { category: 'Arithmethic', name: 'MOD' },
  0x07: { category: 'Arithmethic', name: 'SMOD' },
  0x08: { category: 'Arithmethic', name: 'ADDMOD' },
  0x09: { category: 'Arithmethic', name: 'MULMOD' },
  0x0a: { category: 'Arithmethic', name: 'EXP' },
  0x0b: { category: 'Arithmethic', name: 'SIGNEXTEND' },
  // Comparison
  0x10: { category: 'Comparison', name: 'LT' },
  0x11: { category: 'Comparison', name: 'GT' },
  0x12: { category: 'Comparison', name: 'SLT' },
  0x13: { category: 'Comparison', name: 'SGT' },
  0x14: { category: 'Comparison', name: 'EQ' },
  // Bitwise
  0x15: { category: 'Bitwise', name: 'ISZERO' },
  0x16: { category: 'Bitwise', name: 'AND' },
  0x17: { category: 'Bitwise', name: 'OR' },
  0x18: { category: 'Bitwise', name: 'XOR' },
  0x19: { category: 'Bitwise', name: 'NOT' },
  0x1a: { category: 'Bitwise', name: 'BYTE' },
  0x1b: { category: 'Bitwise', name: 'SHL' },
  0x1c: { category: 'Bitwise', name: 'SHR' },
  0x1d: { category: 'Bitwise', name: 'SAR' },
  // SHA3
  0x20: { category: 'SHA3', name: 'SHA3' },
  // Environmental information
  0x30: { category: 'Environmental information', name: 'ADDRESS' },
  0x31: { category: 'Environmental information', name: 'BALANCE' },
  0x32: { category: 'Environmental information', name: 'ORIGIN' },
  0x33: { category: 'Environmental information', name: 'CALLER' },
  0x34: { category: 'Environmental information', name: 'CALLVALUE' },
  0x35: { category: 'Environmental information', name: 'CALLDATALOAD' },
  0x36: { category: 'Environmental information', name: 'CALLDATASIZE' },
  0x37: { category: 'Environmental information', name: 'CALLDATACOPY' },
  0x38: { category: 'Environmental information', name: 'CODESIZE' },
  0x39: { category: 'Environmental information', name: 'CODECOPY' },
  0x3a: { category: 'Environmental information', name: 'GASPRICE' },
  0x3b: { category: 'Environmental information', name: 'EXTCODESIZE' },
  0x3c: { category: 'Environmental information', name: 'EXTCODECOPY' },
  0x3d: { category: 'Environmental information', name: 'RETURNDATASIZE' },
  0x3e: { category: 'Environmental information', name: 'RETURNDATACOPY' },
  0x3f: { category: 'Environmental information', name: 'EXTCODEHASH' },
  // Block information
  0x40: { category: 'Block information', name: 'BLOCKHASH' },
  0x41: { category: 'Block information', name: 'COINBASE' },
  0x42: { category: 'Block information', name: 'TIMESTAMP' },
  0x43: { category: 'Block information', name: 'NUMER' },
  0x44: { category: 'Block information', name: 'PREVRANDAO' },
  0x45: { category: 'Block information', name: 'GASLIMIT' },
  0x46: { category: 'Block information', name: 'CHAINID' },
  0x47: { category: 'Block information', name: 'SELFBALANCE' },
  0x48: { category: 'Block information', name: 'BASEFEE' },
  // Memory
  0x51: { category: 'Memory', name: 'MLOAD' },
  0x52: { category: 'Memory', name: 'MSTORE' },
  0x53: { category: 'Memory', name: 'MSTORE8' },
  0x59: { category: 'Memory', name: 'MSIZE' },
  // Storage
  0x54: { category: 'Storage', name: 'SLOAD' },
  0x55: { category: 'Storage', name: 'SSTORE' },
  // Stack and flow
  0x50: { category: 'Stack and flow', name: 'POP' },
  0x56: { category: 'Stack and flow', name: 'JUMP' },
  0x57: { category: 'Stack and flow', name: 'JUMPI' },
  0x58: { category: 'Stack and flow', name: 'PC' },
  0x5a: { category: 'Stack and flow', name: 'GAS' },
  0x5b: { category: 'Stack and flow', name: 'JUMPDEST' },
  // Push
  0x5f: { category: 'Push', name: 'PUSH0' },
  0x60: { category: 'Push', name: 'PUSH1' },
  0x61: { category: 'Push', name: 'PUSH2' },
  0x62: { category: 'Push', name: 'PUSH3' },
  0x63: { category: 'Push', name: 'PUSH4' },
  0x64: { category: 'Push', name: 'PUSH5' },
  0x65: { category: 'Push', name: 'PUSH6' },
  0x66: { category: 'Push', name: 'PUSH7' },
  0x67: { category: 'Push', name: 'PUSH8' },
  0x68: { category: 'Push', name: 'PUSH9' },
  0x69: { category: 'Push', name: 'PUSH10' },
  0x6a: { category: 'Push', name: 'PUSH11' },
  0x6b: { category: 'Push', name: 'PUSH12' },
  0x6c: { category: 'Push', name: 'PUSH13' },
  0x6d: { category: 'Push', name: 'PUSH14' },
  0x6e: { category: 'Push', name: 'PUSH15' },
  0x6f: { category: 'Push', name: 'PUSH16' },
  0x70: { category: 'Push', name: 'PUSH17' },
  0x71: { category: 'Push', name: 'PUSH18' },
  0x72: { category: 'Push', name: 'PUSH19' },
  0x73: { category: 'Push', name: 'PUSH20' },
  0x74: { category: 'Push', name: 'PUSH21' },
  0x75: { category: 'Push', name: 'PUSH22' },
  0x76: { category: 'Push', name: 'PUSH23' },
  0x77: { category: 'Push', name: 'PUSH24' },
  0x78: { category: 'Push', name: 'PUSH25' },
  0x79: { category: 'Push', name: 'PUSH26' },
  0x7a: { category: 'Push', name: 'PUSH27' },
  0x7b: { category: 'Push', name: 'PUSH28' },
  0x7c: { category: 'Push', name: 'PUSH29' },
  0x7d: { category: 'Push', name: 'PUSH30' },
  0x7e: { category: 'Push', name: 'PUSH31' },
  0x7f: { category: 'Push', name: 'PUSH32' },
  // Duplication
  0x80: { category: 'Duplication', name: 'DUP1' },
  0x81: { category: 'Duplication', name: 'DUP2' },
  0x82: { category: 'Duplication', name: 'DUP3' },
  0x83: { category: 'Duplication', name: 'DUP4' },
  0x84: { category: 'Duplication', name: 'DUP5' },
  0x85: { category: 'Duplication', name: 'DUP6' },
  0x86: { category: 'Duplication', name: 'DUP7' },
  0x87: { category: 'Duplication', name: 'DUP8' },
  0x88: { category: 'Duplication', name: 'DUP9' },
  0x89: { category: 'Duplication', name: 'DUP10' },
  0x8a: { category: 'Duplication', name: 'DUP11' },
  0x8b: { category: 'Duplication', name: 'DUP12' },
  0x8c: { category: 'Duplication', name: 'DUP13' },
  0x8d: { category: 'Duplication', name: 'DUP14' },
  0x8e: { category: 'Duplication', name: 'DUP15' },
  0x8f: { category: 'Duplication', name: 'DUP16' },
  // Swap
  0x90: { category: 'Swap', name: 'SWAP1' },
  0x91: { category: 'Swap', name: 'SWAP2' },
  0x92: { category: 'Swap', name: 'SWAP3' },
  0x93: { category: 'Swap', name: 'SWAP4' },
  0x94: { category: 'Swap', name: 'SWAP5' },
  0x95: { category: 'Swap', name: 'SWAP6' },
  0x96: { category: 'Swap', name: 'SWAP7' },
  0x97: { category: 'Swap', name: 'SWAP8' },
  0x98: { category: 'Swap', name: 'SWAP9' },
  0x99: { category: 'Swap', name: 'SWAP10' },
  0x9a: { category: 'Swap', name: 'SWAP11' },
  0x9b: { category: 'Swap', name: 'SWAP12' },
  0x9c: { category: 'Swap', name: 'SWAP13' },
  0x9d: { category: 'Swap', name: 'SWAP14' },
  0x9e: { category: 'Swap', name: 'SWAP15' },
  0x9f: { category: 'Swap', name: 'SWAP16' },
  // Logging
  0xa0: { category: 'Logging', name: 'LOG0' },
  0xa1: { category: 'Logging', name: 'LOG1' },
  0xa2: { category: 'Logging', name: 'LOG2' },
  0xa3: { category: 'Logging', name: 'LOG3' },
  0xa4: { category: 'Logging', name: 'LOG4' },
  // System
  0xf0: { category: 'System', name: 'CREATE' },
  0xf1: { category: 'System', name: 'CALL' },
  0xf2: { category: 'System', name: 'CALLCODE' },
  0xf3: { category: 'System', name: 'RETURN' },
  0xf4: { category: 'System', name: 'DELEGATECALL' },
  0xf5: { category: 'System', name: 'CREATE2' },
  0xfa: { category: 'System', name: 'STATICCALL' },
  0xfd: { category: 'System', name: 'REVERT' },
  0xfe: { category: 'System', name: 'INVALID' },
  0xff: { category: 'System', name: 'SELFDESTRUCT' },
};
