export const switchStyles = [
  'peer',
  'inline-flex',
  'h-6',
  'w-11',
  'shrink-0',
  'cursor-pointer',
  'items-center',
  'rounded-full',
  'border-2',
  'border-transparent',
  'transition-colors',
  'focus-visible:outline-none',
  'focus-visible:ring-2',
  'focus-visible:ring-blue-250',
  'disabled:cursor-not-allowed',
  'disabled:opacity-50',
  'data-[state=checked]:bg-blue-250',
  'data-[state=unchecked]:bg-gray-350',
];

export const switchThumbStyles = [
  'pointer-events-none',
  'block',
  'h-5',
  'w-5',
  'rounded-full',
  'shadow-lg',
  'ring-0',
  'transition-all',
  'data-[state=checked]:translate-x-5',
  'data-[state=unchecked]:translate-x-0',
  'data-[state=checked]:bg-gray-100',
  'data-[state=unchecked]:bg-gray-150',
];
